create Money and Airlines
AndreyShl/homework pull request #5
Opened 2024-10-22 22:41 UTC by AndreyShl

2024-10-24 11:25 UTC, PavelIvanouski requested changes

2024-10-24 11:25 UTC, PavelIvanouski commented on src/homeworkOOP/Money/Money.java
> +    public String rubIndex;
зачем отдлельнве переменные для rubIndex, sentIndex?
можно просто в отдельном методе определять нужные окончания

2024-10-24 11:25 UTC, PavelIvanouski commented on src/homeworkOOP/airLine/Airport.java
> +    public String findEqualPlane(int seat, int capacityUP) {
почему String? можно ведь возвращать AirVehicle[]

2024-10-24 19:30 UTC, AndreyShl commented on src/homeworkOOP/airLine/Airport.java
> +    public String findEqualPlane(int seat, int capacityUP) {
Исправлено, я просто это делал с точки удобства вывода, но согласен лучше иметь массив

2024-10-26 16:55 UTC, PavelIvanouski commented on src/homeworkOOP/Money/Money.java
> +        return equalWallOrNot;
можно одной строкой
return this.rub == secondWallet.rub && this.cent == secondWallet.cent;
тогда переменная equalWallOrNot не нужна

2024-10-26 16:56 UTC, PavelIvanouski approved these changes

2024-10-27 22:14 UTC, merged