homeworkRegEx
AndreyShl/homework pull request #7
Opened 2024-10-27 22:13 UTC by AndreyShl

2024-10-27 22:17 UTC, AndreyShl commented
Я честно не понимаю почему я выбираю только два файла для пуша, а пишет что я все файлы заново сделал, хотя выбирал именно те которые нужны, может ли это быть из-за того что я каждый раз создаю новую ветку а не работаю с одной веткой Homework?
![изображение_2024-10-28_011708585](https://github.com/user-attachments/assets/6a1191ec-dc19-4dd4-8e42-0c9eacf7276a)

2024-11-06 08:23 UTC, PavelIvanouski requested changes

2024-11-06 08:23 UTC, PavelIvanouski commented on src/homeworkRegEx/Main.java
> +        StringBuilder stringBuilder = new StringBuilder(string);
зачем StringBuilder? можно ведь по строке пройтись?

2024-11-06 08:23 UTC, PavelIvanouski commented on src/homeworkRegEx/StrPollinomOrNot.java
> +public class StrPollinomOrNot {
обычно так метод назыdают, а не класс. лучше класс называть StringUtil или Util

2024-11-23 12:57 UTC, merged